/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowToRouteImport } from './routes/how-to'
import { Route as IphoneRouteImport } from './routes/iphone'
import { Route as LimitsRouteImport } from './routes/limits'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as PortraitsRouteImport } from './routes/portraits'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductPhotosRouteImport } from './routes/product-photos'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as TransparentPngRouteImport } from './routes/transparent-png'
import { Route as WhiteBackgroundRouteImport } from './routes/white-background'
import { Route as BackdropRouteImport } from './routes/backdrop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToRoute = HowToRouteImport.update({
  id: '/how-to',
  path: '/how-to',
  getParentRoute: () => rootRouteImport,
} as any)
const IphoneRoute = IphoneRouteImport.update({
  id: '/iphone',
  path: '/iphone',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitsRoute = LimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const PortraitsRoute = PortraitsRouteImport.update({
  id: '/portraits',
  path: '/portraits',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPhotosRoute = ProductPhotosRouteImport.update({
  id: '/product-photos',
  path: '/product-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparentPngRoute = TransparentPngRouteImport.update({
  id: '/transparent-png',
  path: '/transparent-png',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteBackgroundRoute = WhiteBackgroundRouteImport.update({
  id: '/white-background',
  path: '/white-background',
  getParentRoute: () => rootRouteImport,
} as any)
const BackdropRoute = BackdropRouteImport.update({
  id: '/backdrop',
  path: '/backdrop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to': typeof HowToRoute
  '/iphone': typeof IphoneRoute
  '/limits': typeof LimitsRoute
  '/marketplace': typeof MarketplaceRoute
  '/portraits': typeof PortraitsRoute
  '/privacy': typeof PrivacyRoute
  '/product-photos': typeof ProductPhotosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/whatsapp': typeof WhatsappRoute
  '/transparent-png': typeof TransparentPngRoute
  '/white-background': typeof WhiteBackgroundRoute
  '/backdrop': typeof BackdropRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to': typeof HowToRoute
  '/iphone': typeof IphoneRoute
  '/limits': typeof LimitsRoute
  '/marketplace': typeof MarketplaceRoute
  '/portraits': typeof PortraitsRoute
  '/privacy': typeof PrivacyRoute
  '/product-photos': typeof ProductPhotosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/whatsapp': typeof WhatsappRoute
  '/transparent-png': typeof TransparentPngRoute
  '/white-background': typeof WhiteBackgroundRoute
  '/backdrop': typeof BackdropRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-to': typeof HowToRoute
  '/iphone': typeof IphoneRoute
  '/limits': typeof LimitsRoute
  '/marketplace': typeof MarketplaceRoute
  '/portraits': typeof PortraitsRoute
  '/privacy': typeof PrivacyRoute
  '/product-photos': typeof ProductPhotosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/whatsapp': typeof WhatsappRoute
  '/transparent-png': typeof TransparentPngRoute
  '/white-background': typeof WhiteBackgroundRoute
  '/backdrop': typeof BackdropRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-to'
    | '/iphone'
    | '/limits'
    | '/marketplace'
    | '/portraits'
    | '/privacy'
    | '/product-photos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/whatsapp'
    | '/transparent-png'
    | '/white-background'
    | '/backdrop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-to'
    | '/iphone'
    | '/limits'
    | '/marketplace'
    | '/portraits'
    | '/privacy'
    | '/product-photos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/whatsapp'
    | '/transparent-png'
    | '/white-background'
    | '/backdrop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-to'
    | '/iphone'
    | '/limits'
    | '/marketplace'
    | '/portraits'
    | '/privacy'
    | '/product-photos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/whatsapp'
    | '/transparent-png'
    | '/white-background'
    | '/backdrop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowToRoute: typeof HowToRoute
  IphoneRoute: typeof IphoneRoute
  LimitsRoute: typeof LimitsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PortraitsRoute: typeof PortraitsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductPhotosRoute: typeof ProductPhotosRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WhatsappRoute: typeof WhatsappRoute
  TransparentPngRoute: typeof TransparentPngRoute
  WhiteBackgroundRoute: typeof WhiteBackgroundRoute
  BackdropRoute: typeof BackdropRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to': {
      id: '/how-to'
      path: '/how-to'
      fullPath: '/how-to'
      preLoaderRoute: typeof HowToRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iphone': {
      id: '/iphone'
      path: '/iphone'
      fullPath: '/iphone'
      preLoaderRoute: typeof IphoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limits': {
      id: '/limits'
      path: '/limits'
      fullPath: '/limits'
      preLoaderRoute: typeof LimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portraits': {
      id: '/portraits'
      path: '/portraits'
      fullPath: '/portraits'
      preLoaderRoute: typeof PortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-photos': {
      id: '/product-photos'
      path: '/product-photos'
      fullPath: '/product-photos'
      preLoaderRoute: typeof ProductPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparent-png': {
      id: '/transparent-png'
      path: '/transparent-png'
      fullPath: '/transparent-png'
      preLoaderRoute: typeof TransparentPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/white-background': {
      id: '/white-background'
      path: '/white-background'
      fullPath: '/white-background'
      preLoaderRoute: typeof WhiteBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backdrop': {
      id: '/backdrop'
      path: '/backdrop'
      fullPath: '/backdrop'
      preLoaderRoute: typeof BackdropRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowToRoute: HowToRoute,
  IphoneRoute: IphoneRoute,
  LimitsRoute: LimitsRoute,
  MarketplaceRoute: MarketplaceRoute,
  PortraitsRoute: PortraitsRoute,
  PrivacyRoute: PrivacyRoute,
  ProductPhotosRoute: ProductPhotosRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WhatsappRoute: WhatsappRoute,
  TransparentPngRoute: TransparentPngRoute,
  WhiteBackgroundRoute: WhiteBackgroundRoute,
  BackdropRoute: BackdropRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
